name: Push Llama3 Flask Containers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build and push images'
            run: |
              docker build ./llm-deployments/llama3/q4/ --tag ghcr.io/civo-learn/llama3-flask-kf-q4:latest
              docker push ghcr.io/civo-learn/llama3-flask-kf-q4:latest

              docker build ./llm-deployments/llama3/q2/ --tag ghcr.io/civo-learn/llama3-flask-kf-q2:latest
              docker push ghcr.io/civo-learn/llama3-flask-kf-q2:latest
              
              docker build ./llm-deployments/llama3/q8/ --tag ghcr.io/civo-learn/llama3-flask-kf-q8:latest
              docker push ghcr.io/civo-learn/llama3-flask-kf-q8:latest
              
              docker build ./llm-deployments/llama2/q4/flask/ --tag ghcr.io/civo-learn/llama2-flask-kf-q4:latest
              docker push ghcr.io/civo-learn/llama2-flask-kf-q4:latest

              docker build ./llm-deployments/llama2/q2/ --tag ghcr.io/civo-learn/llama2-flask-kf-q2:latest
              docker push ghcr.io/civo-learn/llama2-flask-kf-q2:latest
              
              docker build ./llm-deployments/llama2/q8/ --tag ghcr.io/civo-learn/llama2-flask-kf-q8:latest
              docker push ghcr.io/civo-learn/llama2-flask-kf-q8:latest