name: Deploy Flask Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './llm-deployments/llama2/'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v1
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GITHUB_TOKEN}}

          - name: 'Build Inventory Image'
            run: |
              docker build ./q4/flask/ --tag ghcr.io/civo-learn/llama2-flask-kf-q4:latest
              docker push ghcr.io/civo-learn/llama2-flask-kf-q4:latest

              docker build ./q2/ --tag ghcr.io/civo-learn/llama2-flask-kf-q2:latest
              docker push ghcr.io/civo-learn/llama2-flask-kf-q4:latest
              
              docker build ./q8/ --tag ghcr.io/civo-learn/llama2-flask-kf-q8:latest
              docker push ghcr.io/civo-learn/llama2-flask-kf-q4:latest